

# Database
db.url=jdbc:postgresql://localhost:5432/weatherApp
db.username=postgres
db.password=111
db.driver=org.postgresql.Driver

# HikariCP
hikari.maximumPoolSize=10
hikari.minimumIdle=5
hikari.idleTimeout=30000

# Hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=validate
hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
hibernate.scan_packages=io.github.xcvqqz.weather_app.entity

# Thymeleaf - ????????? ??? ??? ??????? ????????????
thymeleaf.cache=false
thymeleaf.prefix=/WEB-INF/templates/
thymeleaf.suffix=.html

# Flyway
flyway.locations=classpath:db/migration

# Scheduler
cleanup.cron.expression=0 */30 * * * *
zone.cron.expression = Europe/Moscow

# Weather API
app.key = 4f9e811e1990b95dd679058a3dfae99a
weather.url = https://api.openweathermap.org/data/2.5/weather
geo.url = https://api.openweathermap.org/geo/1.0/direct