

# Database
db.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
db.username=h2
db.password=
db.driver=org.h2.Driver

# Hibernate
hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=create-drop
hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
hibernate.scan_packages=io.github.xcvqqz.weather_app.entity

# Flyway
flyway.locations=classpath:db/migration