CREATE TABLE Sessions (
    id UUID PRIMARY KEY NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);